// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XPostMonitor.Data;

#nullable disable

namespace XPostMonitor.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730110205_AddLinkTokenSettings")]
    partial class AddLinkTokenSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XPostMonitor.Models.ArcBridgeTransfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BurnIntentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepositBlockNumber")
                        .HasMaxLength(78)
                        .HasColumnType("nvarchar(78)");

                    b.Property<string>("DepositTransactionHash")
                        .HasMaxLength(66)
                        .HasColumnType("nvarchar(66)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GrossAmountAtomic")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("nvarchar(78)");

                    b.Property<string>("MaxFeeAtomic")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("nvarchar(78)");

                    b.Property<string>("MintTransactionHash")
                        .HasMaxLength(66)
                        .HasColumnType("nvarchar(66)");

                    b.Property<string>("ReceiveAmountAtomic")
                        .IsRequired()
                        .HasMaxLength(78)
                        .HasColumnType("nvarchar(78)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "Status");

                    b.ToTable("ArcBridgeTransfers");
                });

            modelBuilder.Entity("XPostMonitor.Models.ArcBridgeWallet", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.HasKey("ChatId");

                    b.ToTable("ArcBridgeWallets");
                });

            modelBuilder.Entity("XPostMonitor.Models.AutoTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(28,20)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("QuoteTokenAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TokenAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TokenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TokenSymbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("TradingWorkerId")
                        .HasColumnType("bigint");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("Status");

                    b.HasIndex("TradingWorkerId");

                    b.ToTable("AutoTrades");
                });

            modelBuilder.Entity("XPostMonitor.Models.AutoTradeOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AutoTradeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GmgnOrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("NotifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProfitPercent")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("RealizedProfitUsd")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("SellPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("decimal(28,20)");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AutoTradeId");

                    b.HasIndex("GmgnOrderId")
                        .IsUnique();

                    b.ToTable("AutoTradeOrders");
                });

            modelBuilder.Entity("XPostMonitor.Models.LinkTokenSettings", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Anchor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("BuyAmount")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CreatorTaxPercent")
                        .HasColumnType("int");

                    b.Property<bool>("EnableAutoCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableAutoTrading")
                        .HasColumnType("bit");

                    b.Property<string>("Launchpad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SlippagePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerCount")
                        .HasColumnType("int");

                    b.HasKey("ChatId");

                    b.ToTable("LinkTokenSettings");
                });

            modelBuilder.Entity("XPostMonitor.Models.TakeProfitSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ProfitPercent")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SellPercent")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "ProfitPercent")
                        .IsUnique();

                    b.ToTable("TakeProfitSettings");
                });

            modelBuilder.Entity("XPostMonitor.Models.TelegramUser", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasDefaultValue("en");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ChatId");

                    b.ToTable("TelegramUsers");
                });

            modelBuilder.Entity("XPostMonitor.Models.TradingWorker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedEvmPrivateKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedGmgnApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedGmgnPrivateKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvmWalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SlotNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "SlotNumber")
                        .IsUnique();

                    b.ToTable("TradingWorkers");
                });

            modelBuilder.Entity("XPostMonitor.Models.UserChainTradingSettings", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Chain")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("BuyAmount")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("SlippagePercent")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ChatId", "Chain");

                    b.ToTable("UserChainTradingSettings");
                });

            modelBuilder.Entity("XPostMonitor.Models.UserTradingSettings", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EnableTokenCreation")
                        .HasColumnType("bit");

                    b.HasKey("ChatId");

                    b.ToTable("UserTradingSettings");
                });

            modelBuilder.Entity("XPostMonitor.Models.WatchlistEntry", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("XUserId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorTaxPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("EnableAutoTrading")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ParallelTokenCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TokenAnchor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TokenChain")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TokenDex")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ChatId", "XUserId");

                    b.HasIndex("XUserId");

                    b.ToTable("WatchlistEntries");
                });

            modelBuilder.Entity("XPostMonitor.Models.XAccount", b =>
                {
                    b.Property<string>("XUserId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastPostId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("TelegramChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("XUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("XAccounts");
                });

            modelBuilder.Entity("XPostMonitor.Models.XSubscription", b =>
                {
                    b.Property<string>("XUserId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EventType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RemoteSubscriptionId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("XUserId", "EventType");

                    b.ToTable("XSubscriptions");
                });

            modelBuilder.Entity("XPostMonitor.Models.ArcBridgeTransfer", b =>
                {
                    b.HasOne("XPostMonitor.Models.ArcBridgeWallet", "Wallet")
                        .WithMany("Transfers")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("XPostMonitor.Models.ArcBridgeWallet", b =>
                {
                    b.HasOne("XPostMonitor.Models.TelegramUser", "TelegramUser")
                        .WithOne("ArcBridgeWallet")
                        .HasForeignKey("XPostMonitor.Models.ArcBridgeWallet", "ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("XPostMonitor.Models.AutoTrade", b =>
                {
                    b.HasOne("XPostMonitor.Models.TelegramUser", "TelegramUser")
                        .WithMany("AutoTrades")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XPostMonitor.Models.TradingWorker", "TradingWorker")
                        .WithMany("AutoTrades")
                        .HasForeignKey("TradingWorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TelegramUser");

                    b.Navigation("TradingWorker");
                });

            modelBuilder.Entity("XPostMonitor.Models.AutoTradeOrder", b =>
                {
                    b.HasOne("XPostMonitor.Models.AutoTrade", "AutoTrade")
                        .WithMany("Orders")
                        .HasForeignKey("AutoTradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutoTrade");
                });

            modelBuilder.Entity("XPostMonitor.Models.LinkTokenSettings", b =>
                {
                    b.HasOne("XPostMonitor.Models.TelegramUser", "TelegramUser")
                        .WithOne("LinkTokenSettings")
                        .HasForeignKey("XPostMonitor.Models.LinkTokenSettings", "ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("XPostMonitor.Models.TakeProfitSetting", b =>
                {
                    b.HasOne("XPostMonitor.Models.TelegramUser", "TelegramUser")
                        .WithMany("TakeProfitSettings")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("XPostMonitor.Models.TradingWorker", b =>
                {
                    b.HasOne("XPostMonitor.Models.TelegramUser", "TelegramUser")
                        .WithMany("TradingWorkers")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("XPostMonitor.Models.UserChainTradingSettings", b =>
                {
                    b.HasOne("XPostMonitor.Models.TelegramUser", "TelegramUser")
                        .WithMany("ChainTradingSettings")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("XPostMonitor.Models.UserTradingSettings", b =>
                {
                    b.HasOne("XPostMonitor.Models.TelegramUser", "TelegramUser")
                        .WithOne("TradingSettings")
                        .HasForeignKey("XPostMonitor.Models.UserTradingSettings", "ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("XPostMonitor.Models.WatchlistEntry", b =>
                {
                    b.HasOne("XPostMonitor.Models.TelegramUser", "TelegramUser")
                        .WithMany("Watchlist")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XPostMonitor.Models.XAccount", "XAccount")
                        .WithMany("Watchers")
                        .HasForeignKey("XUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");

                    b.Navigation("XAccount");
                });

            modelBuilder.Entity("XPostMonitor.Models.XSubscription", b =>
                {
                    b.HasOne("XPostMonitor.Models.XAccount", "XAccount")
                        .WithMany("Subscriptions")
                        .HasForeignKey("XUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("XAccount");
                });

            modelBuilder.Entity("XPostMonitor.Models.ArcBridgeWallet", b =>
                {
                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("XPostMonitor.Models.AutoTrade", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("XPostMonitor.Models.TelegramUser", b =>
                {
                    b.Navigation("ArcBridgeWallet");

                    b.Navigation("AutoTrades");

                    b.Navigation("ChainTradingSettings");

                    b.Navigation("LinkTokenSettings");

                    b.Navigation("TakeProfitSettings");

                    b.Navigation("TradingSettings");

                    b.Navigation("TradingWorkers");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("XPostMonitor.Models.TradingWorker", b =>
                {
                    b.Navigation("AutoTrades");
                });

            modelBuilder.Entity("XPostMonitor.Models.XAccount", b =>
                {
                    b.Navigation("Subscriptions");

                    b.Navigation("Watchers");
                });
#pragma warning restore 612, 618
        }
    }
}
