// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XPostMonitor.Data;

#nullable disable

namespace XPostMonitor.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725065932_AddFourMemeCreatorTax")]
    partial class AddFourMemeCreatorTax
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XPostMonitor.Models.TelegramUser", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasDefaultValue("en");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ChatId");

                    b.ToTable("TelegramUsers");
                });

            modelBuilder.Entity("XPostMonitor.Models.UserChainTradingSettings", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Chain")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("BuyAmount")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("SlippagePercent")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ChatId", "Chain");

                    b.ToTable("UserChainTradingSettings");
                });

            modelBuilder.Entity("XPostMonitor.Models.UserTradingSettings", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EnableTokenCreation")
                        .HasColumnType("bit");

                    b.Property<string>("EncryptedEvmPrivateKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedGmgnApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedGmgnPrivateKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvmWalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.HasKey("ChatId");

                    b.ToTable("UserTradingSettings");
                });

            modelBuilder.Entity("XPostMonitor.Models.WatchlistEntry", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("XUserId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorTaxPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TokenAnchor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TokenChain")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TokenDex")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ChatId", "XUserId");

                    b.HasIndex("XUserId");

                    b.ToTable("WatchlistEntries");
                });

            modelBuilder.Entity("XPostMonitor.Models.XAccount", b =>
                {
                    b.Property<string>("XUserId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastPostId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("TelegramChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("XUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("XAccounts");
                });

            modelBuilder.Entity("XPostMonitor.Models.XSubscription", b =>
                {
                    b.Property<string>("XUserId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EventType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RemoteSubscriptionId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("XUserId", "EventType");

                    b.ToTable("XSubscriptions");
                });

            modelBuilder.Entity("XPostMonitor.Models.UserChainTradingSettings", b =>
                {
                    b.HasOne("XPostMonitor.Models.TelegramUser", "TelegramUser")
                        .WithMany("ChainTradingSettings")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("XPostMonitor.Models.UserTradingSettings", b =>
                {
                    b.HasOne("XPostMonitor.Models.TelegramUser", "TelegramUser")
                        .WithOne("TradingSettings")
                        .HasForeignKey("XPostMonitor.Models.UserTradingSettings", "ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("XPostMonitor.Models.WatchlistEntry", b =>
                {
                    b.HasOne("XPostMonitor.Models.TelegramUser", "TelegramUser")
                        .WithMany("Watchlist")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XPostMonitor.Models.XAccount", "XAccount")
                        .WithMany("Watchers")
                        .HasForeignKey("XUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramUser");

                    b.Navigation("XAccount");
                });

            modelBuilder.Entity("XPostMonitor.Models.XSubscription", b =>
                {
                    b.HasOne("XPostMonitor.Models.XAccount", "XAccount")
                        .WithMany("Subscriptions")
                        .HasForeignKey("XUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("XAccount");
                });

            modelBuilder.Entity("XPostMonitor.Models.TelegramUser", b =>
                {
                    b.Navigation("ChainTradingSettings");

                    b.Navigation("TradingSettings");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("XPostMonitor.Models.XAccount", b =>
                {
                    b.Navigation("Subscriptions");

                    b.Navigation("Watchers");
                });
#pragma warning restore 612, 618
        }
    }
}
